[project]
name="ftk"
version="0.1.0"
authors=[{name="Rui", email="ruippgoncalves@protonmail.com"}]
description=""" """
license={text="MIT"}
dependencies=["jjcli"]

[project.scripts]
ftk-occ="ftk.base:main"
